-- Supabase Dashboard > SQL Editor에서 1회 실행합니다.
-- 이 앱은 Streamlit 서버의 SERVICE ROLE KEY로만 DB에 접근합니다.
-- SERVICE ROLE KEY는 절대 브라우저 코드나 공개 저장소에 넣지 마세요.

create table if not exists public.topics (
  id bigint generated by default as identity primary key,
  title text not null unique,
  position integer not null,
  created_at timestamptz not null default now()
);

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('summary','exam')),
  filename text not null,
  content text default '',
  created_at timestamptz not null default now()
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  source_file text,
  source_page integer,
  year text,
  professor text,
  topic_id bigint references public.topics(id) on delete set null,
  question_type text not null default 'multiple_choice',
  question_text text not null,
  choices jsonb not null default '[]'::jsonb,
  correct_answer text default '',
  explanation text default '',
  created_at timestamptz not null default now()
);

create table if not exists public.attempts (
  id bigint generated by default as identity primary key,
  question_id bigint not null references public.questions(id) on delete cascade,
  answer text default '',
  reasoning text default '',
  confidence text default '애매함',
  is_correct boolean,
  status text not null default 'uncertain',
  ai_feedback text default '',
  attempt_no integer not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_questions_topic on public.questions(topic_id);
create index if not exists idx_attempts_question on public.attempts(question_id);

alter table public.topics enable row level security;
alter table public.documents enable row level security;
alter table public.questions enable row level security;
alter table public.attempts enable row level security;

-- anon/authenticated에 정책을 만들지 않습니다.
-- 서버측 service_role은 RLS를 우회합니다.
